// Transcript readers: turning host log files into the developer's own words.
// Spec: docs/SPEC-V2.md — "Reading transcripts" / "Host coverage".
//
// A user turn must be identified structurally, never by guessing, or the
// user-origin gate collapses. Each reader validates the shape it expects and
// quarantines itself loudly if a host changes format — a reader that silently
// stops matching means the profile stops learning and nobody finds out.
import fs from "fs";
import os from "os";
import path from "path";

/**
 * Machine-authored text that still arrives shaped like a typed user turn.
 * Measured on real history: without these, 31% of the "developer's voice"
 * corpus was Claude Code's own boilerplate.
 */
const WRAPPERS = [
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<command-name>",
  "<command-message>",
  "<system-reminder>",
  "Caveat: The messages below were generated by the user while",
];

const BARE_IMAGE = /^(\[Image #\d+\]\s*)+$/;

/** True if the text is the developer speaking, rather than tooling. */
export function isDeveloperText(text) {
  if (typeof text !== "string") return false;
  const trimmed = text.trim();
  if (!trimmed) return false;
  if (BARE_IMAGE.test(trimmed)) return false;
  return !WRAPPERS.some((wrapper) => text.includes(wrapper));
}

/**
 * `promptSource` values that are not the developer's own voice.
 * `suggestion_accepted` is the subtle one: the developer chose it, but the
 * product wrote it, so counting it teaches the profile its own voice back.
 */
const NON_VOICE_SOURCES = new Set(["sdk", "system", "suggestion_accepted"]);

function readJsonl(file) {
  const lines = fs.readFileSync(file, "utf8").split("\n");
  const records = [];
  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      records.push(JSON.parse(line));
    } catch {
      // A torn line must not discard the rest of a session.
    }
  }
  return records;
}

export const claudeCodeReader = {
  name: "claude-code",
  root: () => path.join(os.homedir(), ".claude", "projects"),

  files(root = claudeCodeReader.root()) {
    if (!fs.existsSync(root)) return [];
    const out = [];
    for (const dir of fs.readdirSync(root)) {
      const full = path.join(root, dir);
      if (!fs.statSync(full).isDirectory()) continue;
      for (const file of fs.readdirSync(full)) {
        if (file.endsWith(".jsonl")) out.push(path.join(full, file));
      }
    }
    return out.sort();
  },

  /**
   * A typed turn is `type === "user"` AND `message.content` is a plain string.
   * Tool results are always a list; injected notices carry `isMeta`. This is a
   * structural test, so the gate holds without heuristics.
   */
  turnsFrom(records, source = "") {
    const turns = [];
    for (const record of records) {
      if (record.type !== "user" || record.isSidechain) continue;
      const content = record.message?.content;
      if (typeof content !== "string") continue;
      if (NON_VOICE_SOURCES.has(record.promptSource)) continue;
      if (!isDeveloperText(content)) continue;

      turns.push({
        host: "claude-code",
        text: content.trim(),
        ts: record.timestamp ? Date.parse(record.timestamp) : null,
        cwd: record.cwd || null,
        session: record.sessionId || null,
        source,
      });
    }
    return turns;
  },

  /** Cheap shape check, so a format change quarantines rather than misreads. */
  validate(records) {
    if (!records.length) return { ok: true };
    const known = records.some((r) => typeof r.type === "string");
    return known
      ? { ok: true }
      : { ok: false, reason: "no `type` field on any record; format may have changed" };
  },
};

export const piReader = {
  name: "pi",
  root: () => path.join(os.homedir(), ".pi", "agent", "sessions"),

  files(root = piReader.root()) {
    if (!fs.existsSync(root)) return [];
    const out = [];
    for (const dir of fs.readdirSync(root)) {
      const full = path.join(root, dir);
      if (!fs.existsSync(full) || !fs.statSync(full).isDirectory()) continue;
      for (const file of fs.readdirSync(full)) {
        if (file.endsWith(".jsonl")) out.push(path.join(full, file));
      }
    }
    return out.sort();
  },

  /** pi tags roles on message blocks, so user turns are directly addressable. */
  turnsFrom(records, source = "") {
    const turns = [];
    for (const record of records) {
      if (record.type !== "message") continue;
      const message = record.message;
      if (!message || message.role !== "user") continue;

      const blocks = Array.isArray(message.content) ? message.content : [];
      const text = blocks
        .filter((b) => b && b.type === "text" && typeof b.text === "string")
        .map((b) => b.text)
        .join("\n")
        .trim();

      if (!isDeveloperText(text)) continue;

      turns.push({
        host: "pi",
        text,
        ts: record.timestamp ? Date.parse(record.timestamp) : null,
        cwd: record.cwd || null,
        session: record.id || null,
        source,
      });
    }
    return turns;
  },

  validate(records) {
    if (!records.length) return { ok: true };
    const known = records.some((r) => r.type === "message" || r.type === "session");
    return known ? { ok: true } : { ok: false, reason: "no recognisable record types" };
  },
};

export const READERS = [claudeCodeReader, piReader];

/**
 * Read every configured host. A reader that fails validation is quarantined —
 * reported, skipped, and never allowed to take the others down with it.
 */
export function readAll({ readers = READERS, roots = {}, cursors = {}, quarantine = [] } = {}) {
  const turns = [];
  const quarantined = [];
  const nextCursors = { ...cursors };
  const alreadyQuarantined = new Set(quarantine.map((q) => q.reader));

  for (const reader of readers) {
    // A quarantined reader stays quarantined until the developer clears it.
    // Retrying every pass would re-warn forever about a format that hasn't
    // changed back.
    if (alreadyQuarantined.has(reader.name)) continue;

    let files;
    try {
      files = reader.files(roots[reader.name]);
    } catch (err) {
      quarantined.push({ reader: reader.name, reason: err.message });
      continue;
    }

    for (const file of files) {
      let stat;
      try {
        stat = fs.statSync(file);
      } catch {
        continue;
      }

      // Per-file cursor: only what was appended since last time. A file that
      // shrank or changed inode is re-read from zero.
      const previous = cursors[file];
      if (previous && previous.size === stat.size && previous.ino === stat.ino) continue;

      let records;
      try {
        records = readJsonl(file);
      } catch (err) {
        quarantined.push({ reader: reader.name, reason: `${file}: ${err.message}` });
        continue;
      }

      const check = reader.validate(records);
      if (!check.ok) {
        quarantined.push({ reader: reader.name, reason: check.reason });
        break;
      }

      turns.push(...reader.turnsFrom(records, file));
      nextCursors[file] = { size: stat.size, ino: stat.ino };
    }
  }

  turns.sort((a, b) => (a.ts || 0) - (b.ts || 0));
  return { turns, quarantined, cursors: nextCursors };
}
