// The user-origin gate. Densest coverage in the project, deliberately:
// everything downstream trusts that these turns are the developer's own words.
// Spec: docs/SPEC-V2.md — "Reading transcripts".
import assert from "assert";
import fs from "fs";
import os from "os";
import path from "path";
import { claudeCodeReader, piReader, readAll, isDeveloperText } from "../src/lib/readers.js";

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    console.log(`  ✓ ${name}`);
  } catch (e) {
    failed++;
    console.log(`  ✗ ${name}: ${e.message}`);
  }
}

const texts = (turns) => turns.map((t) => t.text);

console.log("\nreaders: claude code — what counts as the developer");

const TYPED = {
  type: "user",
  timestamp: "2026-07-20T06:30:00.000Z",
  cwd: "/Users/dev/project",
  sessionId: "s1",
  promptSource: "typed",
  message: { role: "user", content: "Lets continue to the next" },
};

test("keeps a genuinely typed turn", () => {
  assert.deepStrictEqual(texts(claudeCodeReader.turnsFrom([TYPED])), ["Lets continue to the next"]);
});

test("drops a tool result (content is a list)", () => {
  const record = {
    type: "user",
    message: { role: "user", content: [{ type: "tool_result", content: "file listing" }] },
  };
  assert.deepStrictEqual(claudeCodeReader.turnsFrom([record]), []);
});

test("drops an injected meta notice", () => {
  const record = {
    type: "user",
    isMeta: true,
    message: { role: "user", content: [{ type: "text", text: "The user started installing…" }] },
  };
  assert.deepStrictEqual(claudeCodeReader.turnsFrom([record]), []);
});

test("drops assistant records", () => {
  assert.deepStrictEqual(
    claudeCodeReader.turnsFrom([{ type: "assistant", message: { role: "assistant", content: "hi" } }]),
    []
  );
});

test("drops sub-agent turns", () => {
  assert.deepStrictEqual(claudeCodeReader.turnsFrom([{ ...TYPED, isSidechain: true }]), []);
});

for (const source of ["sdk", "system", "suggestion_accepted"]) {
  test(`drops promptSource "${source}"`, () => {
    assert.deepStrictEqual(claudeCodeReader.turnsFrom([{ ...TYPED, promptSource: source }]), []);
  });
}

test("keeps a turn with no promptSource (older records)", () => {
  const { promptSource, ...older } = TYPED;
  assert.strictEqual(claudeCodeReader.turnsFrom([older]).length, 1);
});

console.log("\nreaders: machine text wearing a user turn's shape");

const WRAPPED = {
  "local command output": "<local-command-stdout>total 48\ndrwxr-xr-x</local-command-stdout>",
  "local command caveat":
    "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these",
  "slash command name": "<command-name>/wayfinder</command-name>",
  "slash command message": "<command-message>wayfinder</command-message>",
  "system reminder": "<system-reminder>As you answer, use the following context</system-reminder>",
  "bare image paste": "[Image #1]",
  "several bare images": "[Image #1] [Image #2]",
  "empty string": "   ",
};

for (const [label, content] of Object.entries(WRAPPED)) {
  test(`drops ${label}`, () => {
    const record = { ...TYPED, message: { role: "user", content } };
    assert.deepStrictEqual(claudeCodeReader.turnsFrom([record]), [], `${label} leaked through`);
  });
}

test("keeps prose that merely mentions a tag name", () => {
  const record = {
    ...TYPED,
    message: { role: "user", content: "why does the system reminder keep firing?" },
  };
  assert.strictEqual(claudeCodeReader.turnsFrom([record]).length, 1);
});

test("isDeveloperText is safe on non-strings", () => {
  assert.strictEqual(isDeveloperText(null), false);
  assert.strictEqual(isDeveloperText(42), false);
  assert.strictEqual(isDeveloperText(undefined), false);
});

console.log("\nreaders: metadata");

test("carries timestamp, cwd and session", () => {
  const [turn] = claudeCodeReader.turnsFrom([TYPED]);
  assert.strictEqual(turn.ts, Date.parse("2026-07-20T06:30:00.000Z"));
  assert.strictEqual(turn.cwd, "/Users/dev/project");
  assert.strictEqual(turn.session, "s1");
  assert.strictEqual(turn.host, "claude-code");
});

console.log("\nreaders: pi");

test("keeps a role-tagged user message", () => {
  const record = {
    type: "message",
    timestamp: "2026-07-20T09:00:00.000Z",
    message: { role: "user", content: [{ type: "text", text: "check the failing test" }] },
  };
  assert.deepStrictEqual(texts(piReader.turnsFrom([record])), ["check the failing test"]);
});

test("drops assistant messages", () => {
  const record = {
    type: "message",
    message: { role: "assistant", content: [{ type: "text", text: "sure" }] },
  };
  assert.deepStrictEqual(piReader.turnsFrom([record]), []);
});

test("drops non-message records", () => {
  assert.deepStrictEqual(piReader.turnsFrom([{ type: "model_change", provider: "x" }]), []);
});

test("ignores non-text blocks", () => {
  const record = {
    type: "message",
    message: {
      role: "user",
      content: [{ type: "image", data: "…" }, { type: "text", text: "look at this" }],
    },
  };
  assert.deepStrictEqual(texts(piReader.turnsFrom([record])), ["look at this"]);
});

console.log("\nreaders: quarantine and cursors");

function fixtureRoot(records, { dir = "proj", file = "s.jsonl" } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "specificity-reader-"));
  fs.mkdirSync(path.join(root, dir), { recursive: true });
  fs.writeFileSync(
    path.join(root, dir, file),
    records.map((r) => JSON.stringify(r)).join("\n") + "\n"
  );
  return root;
}

test("reads through the registry", () => {
  const root = fixtureRoot([TYPED]);
  const { turns, quarantined } = readAll({
    readers: [claudeCodeReader],
    roots: { "claude-code": root },
  });
  assert.deepStrictEqual(texts(turns), ["Lets continue to the next"]);
  assert.deepStrictEqual(quarantined, []);
});

test("a torn line does not lose the rest of the session", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "specificity-torn-"));
  fs.mkdirSync(path.join(root, "proj"));
  fs.writeFileSync(
    path.join(root, "proj", "s.jsonl"),
    JSON.stringify(TYPED) + "\n{ this is not json\n" + JSON.stringify(TYPED) + "\n"
  );
  const { turns } = readAll({ readers: [claudeCodeReader], roots: { "claude-code": root } });
  assert.strictEqual(turns.length, 2);
});

test("an unrecognisable format quarantines the reader instead of misreading", () => {
  const root = fixtureRoot([{ nope: 1 }, { also: 2 }]);
  const { turns, quarantined } = readAll({
    readers: [claudeCodeReader],
    roots: { "claude-code": root },
  });
  assert.deepStrictEqual(turns, []);
  assert.strictEqual(quarantined.length, 1);
  assert.match(quarantined[0].reason, /format may have changed/);
});

test("one broken reader does not take down the others", () => {
  const good = fixtureRoot([TYPED]);
  const broken = { name: "boom", files: () => { throw new Error("unreadable"); } };
  const { turns, quarantined } = readAll({
    readers: [broken, claudeCodeReader],
    roots: { "claude-code": good },
  });
  assert.strictEqual(turns.length, 1);
  assert.strictEqual(quarantined.length, 1);
});

test("a cursor skips a file that has not grown", () => {
  const root = fixtureRoot([TYPED]);
  const first = readAll({ readers: [claudeCodeReader], roots: { "claude-code": root } });
  assert.strictEqual(first.turns.length, 1);

  const second = readAll({
    readers: [claudeCodeReader],
    roots: { "claude-code": root },
    cursors: first.cursors,
  });
  assert.strictEqual(second.turns.length, 0, "unchanged file should be skipped");
});

test("appended content is picked up on the next pass", () => {
  const root = fixtureRoot([TYPED]);
  const first = readAll({ readers: [claudeCodeReader], roots: { "claude-code": root } });

  const file = path.join(root, "proj", "s.jsonl");
  fs.appendFileSync(file, JSON.stringify({ ...TYPED, message: { role: "user", content: "and again" } }) + "\n");

  const second = readAll({
    readers: [claudeCodeReader],
    roots: { "claude-code": root },
    cursors: first.cursors,
  });
  assert.ok(texts(second.turns).includes("and again"));
});

test("turns come back in time order", () => {
  const early = { ...TYPED, timestamp: "2026-07-20T06:00:00.000Z", message: { role: "user", content: "first" } };
  const late = { ...TYPED, timestamp: "2026-07-20T18:00:00.000Z", message: { role: "user", content: "second" } };
  const root = fixtureRoot([late, early]);
  const { turns } = readAll({ readers: [claudeCodeReader], roots: { "claude-code": root } });
  assert.deepStrictEqual(texts(turns), ["first", "second"]);
});

test("a missing root is not an error", () => {
  const { turns, quarantined } = readAll({
    readers: [claudeCodeReader],
    roots: { "claude-code": "/nowhere/at/all" },
  });
  assert.deepStrictEqual(turns, []);
  assert.deepStrictEqual(quarantined, []);
});

console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed > 0 ? 1 : 0);
